package com.examples.weibao.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.examples.weibao.beans.PreferencesBean;

import com.examples.weibao.beans.PreferencesBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig preferencesBeanDaoConfig;

    private final PreferencesBeanDao preferencesBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        preferencesBeanDaoConfig = daoConfigMap.get(PreferencesBeanDao.class).clone();
        preferencesBeanDaoConfig.initIdentityScope(type);

        preferencesBeanDao = new PreferencesBeanDao(preferencesBeanDaoConfig, this);

        registerDao(PreferencesBean.class, preferencesBeanDao);
    }
    
    public void clear() {
        preferencesBeanDaoConfig.clearIdentityScope();
    }

    public PreferencesBeanDao getPreferencesBeanDao() {
        return preferencesBeanDao;
    }

}
